-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 19:31:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tarea_semana_4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tarea_semana_4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarea_semana_4` DEFAULT CHARACTER SET utf8 ;
USE `tarea_semana_4` ;

-- -----------------------------------------------------
-- Table `tarea_semana_4`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_4`.`cursos` (
  `id_curso` INT NOT NULL,
  `nombre_curso` VARCHAR(200) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea_semana_4`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_4`.`estudiantes` (
  `id_estudiantes` INT NOT NULL,
  `nombre_estudiante` VARCHAR(200) NULL,
  `apellido_estudiante` VARCHAR(200) NULL,
  PRIMARY KEY (`id_estudiantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea_semana_4`.`cursos_has_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_4`.`cursos_has_estudiantes` (
  `cursos_id_curso` INT NOT NULL,
  `estudiantes_id_estudiantes` INT NOT NULL,
  PRIMARY KEY (`cursos_id_curso`, `estudiantes_id_estudiantes`),
  INDEX `fk_cursos_has_estudiantes_estudiantes1_idx` (`estudiantes_id_estudiantes` ASC) VISIBLE,
  INDEX `fk_cursos_has_estudiantes_cursos_idx` (`cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_estudiantes_cursos`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `tarea_semana_4`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_estudiantes_estudiantes1`
    FOREIGN KEY (`estudiantes_id_estudiantes`)
    REFERENCES `tarea_semana_4`.`estudiantes` (`id_estudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
